**Problem 1**

Import Numpy as np

In [2]:
import numpy as np


**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [9]:
array1 =  np.array([0,1,2,3,4,5,6,7,8,9])
print(array1)

[0 1 2 3 4 5 6 7 8 9]


**Problem 3**

Create a 3×3 numpy array of all True’s.

**Problem 4**

Extract all odd numbers from arr.

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
b= arr[arr%2 != 0]
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 3 5 7 9]


**Problem 5**

Replace all odd numbers in arr with -1.

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [15]:
np.arange(10)
a = np.reshape(np.arange(10), (5,2))
print(a)



[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**Problem 7** 

Stack arrays a and b vertically.

In [20]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print(b)

output = np.vstack((a,b))
print(output)
print(type(output))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
<class 'numpy.ndarray'>


**Problem 8**

Stack the arrays a and b horizontally.

In [19]:
hor_output = np.hstack((a,b))
print(hor_output)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


**Problem 9**

Get the common items between a and b.

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


**Problem 10**

From array a remove all items present in array b

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)


array([1, 2, 3, 4])

**Problem 11**

Get the positions where elements of a and b match

In [40]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(a==b)

print(np.equal(a,b))
print(np.where(a==b))

[False  True False  True False  True False  True False False]
[False  True False  True False  True False  True False False]
(array([1, 3, 5, 7], dtype=int64),)


**Problem 12** 

Get all items between 5 and 10 from a.

In [56]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

b = a[(a>5)&(a<10)]
print(b)


[6 9]


**Problem 13**

Swap columns 1 and 2 in the array arr.

In [82]:
arr = np.arange(9).reshape(3,3)
print(arr)
print()

#this is how you access the elements in 2D arrays
print(arr[:,[0,2]])

print()
print()
arr[:,[0,1]] = arr[:,[1,0]] 
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 2]
 [3 5]
 [6 8]]


[[1 0 2]
 [4 3 5]
 [7 6 8]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [99]:
arr = np.arange(9).reshape(3,3)
print(arr)
print()

arr[[0,1]] = arr[[1,0]]


print()
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[3 4 5]
 [0 1 2]
 [6 7 8]]


**Problem 15**

Reverse the rows of a 2D array arr.

In [102]:
arr = np.arange(9).reshape(3,3)
print(arr)

print(np.flip(arr, 0))

print(np.flip(arr, 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


**Problem 16**

Reverse the columns of a 2D array arr.

In [104]:
arr = np.arange(9).reshape(3,3)
print(arr)

print(np.fliplr(arr))

print(np.flipud(arr))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [121]:
import random
arr = np.random.random(size = 15)
print(arr)
rand_arr = (arr * 5) + 5 # use arithmetic to push between 5 and 10
print(rand_arr.reshape(5, 3)) # reshape


# find what is random.uniform()
print()
print(np.random.uniform(5,10,[5,3]))

[0.1595 0.5244 0.5639 0.3719 0.161  0.9162 0.6066 0.9152 0.6195 0.2457
 0.1877 0.6825 0.9593 0.782  0.4841]
[[5.7977 7.6219 7.8197]
 [6.8593 5.8049 9.5808]
 [8.0328 9.5758 8.0973]
 [6.2284 5.9384 8.4125]
 [9.7967 8.9101 7.4205]]

[[6.6617 7.6132 9.6735]
 [5.4877 5.4049 7.7412]
 [6.9332 9.196  8.9714]
 [9.6998 5.5638 6.7387]
 [6.3632 6.5563 6.673 ]]


**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [123]:
np.set_printoptions(precision=3)
print(np.random.uniform(5,10,[5,3]))

'''But regarding the np.random.random()

The right-most random() is a function within a sub module of the numpy library called random.

just like np.random.uniform()

just like newyork city within newyork state
just like Singapore city within Singapore
just like Kathmandu within Kathmandu Valley'''

[[5.064 9.741 5.784]
 [6.433 7.876 6.765]
 [6.045 9.34  5.456]
 [6.114 9.433 6.114]
 [9.297 7.881 9.234]]
